### ISSUE TITLE
Bug with percentage based values

### ISSUE THREAD

**Issue by sjusaitis** [nandorojo/moti#45]
When trying to use percentage based values in a Moti View's `animate` prop, I am getting errors of the format `JSON value '50' of type NSString cannot be converted to a ABI40_0_0YGValue. Did you forget the % or pt suffix?`

For example, this throws an error:

```
<MotiView animate={{ left: value ? '0%' : '50%' }} />
```

**Comment by nandorojo** [comment]
Are strings allowed in reanimated?

**Comment by sjusaitis** [comment]
Reanimated's `interpolate` doesn't currently handle them directly, but can be worked around like
```
  const animatedStyle = useAnimatedStyle(() => {
    const left = interpolate(transition.value, [0, 1], [0, 50]);
    const width = interpolate(transition.value, [0, 1], [25, 50]);
    return {
      left: `${left}%`,
      width: `${width}%`,
    };
  });
```

This would add a lot of convenience if Moti could handle them gracefully! Would it be something you think you would add?

**Comment by nandorojo** [comment]
Unfortunately that doesn't fit the paradigm moti uses for animations. We don't interpolate values, because there's no value to interpolate. Instead, we just generate a style object in useAnimatedStyle based on from, animate and exit object props.

The best solution here would be for Reanimated 2 to support these values. Otherwise you'll have to use Reanimated directly.

Using shared values in the animate prop is something I'm interested in, though. It would allow us to interpolate values and such. It's a bit more complicated though, since the prop now needs to accept a worklet too. I'll let you know if I make any progress on that.

**Comment by sjusaitis** [comment]
Actually, in looking into it further, Reanimated 2 _does_ support percentage based values from 2.0.0-rc.2. I had been restricted to 2.0.0-rc.0, where it was failing.

At a quick test with Reanimated 2.0.0 stable and Moti percentage based values are working as expected!

**Comment by nandorojo** [comment]
Awesome! Thanks for the update.
